# Generated by Django 5.2.13 on 2026-04-10 07:00

import apps.core.encryption
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("codes", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allergen", models.CharField(max_length=200)),
                (
                    "allergy_type",
                    models.CharField(
                        choices=[
                            ("drug", "Drug"),
                            ("food", "Food"),
                            ("environmental", "Environmental"),
                            ("other", "Other"),
                        ],
                        default="drug",
                        max_length=15,
                    ),
                ),
                (
                    "reaction",
                    models.TextField(help_text="Description of allergic reaction"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("life_threatening", "Life Threatening"),
                        ],
                        max_length=20,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="patients.patient",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_allergies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Allergies",
                "ordering": ["-severity", "allergen"],
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("inpatient", "Inpatient"),
                            ("outpatient", "Outpatient"),
                            ("emergency", "Emergency"),
                            ("observation", "Observation"),
                            ("telehealth", "Telehealth"),
                        ],
                        max_length=15,
                    ),
                ),
                ("admission_date", models.DateTimeField()),
                ("discharge_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("discharged", "Discharged"),
                            ("transferred", "Transferred"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("chief_complaint", models.TextField()),
                (
                    "discharge_summary",
                    apps.core.encryption.EncryptedTextField(blank=True),
                ),
                ("discharge_disposition", models.CharField(blank=True, max_length=100)),
                ("readmission_risk_score", models.FloatField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounter",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "attending_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attended_encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-admission_date"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diagnosis_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("admitting", "Admitting"),
                            ("working", "Working"),
                        ],
                        default="primary",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "icd10_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnoses",
                        to="codes.icd10code",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="clinical.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Diagnoses",
                "ordering": ["diagnosis_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("progress", "Progress Note"),
                            ("admission", "Admission Note"),
                            ("discharge", "Discharge Note"),
                            ("consultation", "Consultation Note"),
                            ("procedure", "Procedure Note"),
                            ("nursing", "Nursing Note"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "subjective",
                    apps.core.encryption.EncryptedTextField(
                        blank=True, help_text="Patient's reported symptoms"
                    ),
                ),
                (
                    "objective",
                    apps.core.encryption.EncryptedTextField(
                        blank=True, help_text="Clinical findings and observations"
                    ),
                ),
                (
                    "assessment",
                    apps.core.encryption.EncryptedTextField(
                        blank=True, help_text="Clinical assessment and diagnosis"
                    ),
                ),
                (
                    "plan",
                    apps.core.encryption.EncryptedTextField(
                        blank=True, help_text="Treatment plan"
                    ),
                ),
                ("is_signed", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_notes",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="°F",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(blank=True, help_text="bpm", null=True),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(blank=True, help_text="mmHg", null=True),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, help_text="mmHg", null=True),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(blank=True, help_text="breaths/min", null=True),
                ),
                (
                    "oxygen_saturation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="%",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "pain_level",
                    models.IntegerField(
                        blank=True, help_text="Pain scale 0-10", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_vitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vitals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["patient", "-admission_date"],
                name="clinical_en_patient_b31679_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["attending_doctor", "-admission_date"],
                name="clinical_en_attendi_befe34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(fields=["status"], name="clinical_en_status_fcc7c5_idx"),
        ),
        migrations.AddIndex(
            model_name="progressnote",
            index=models.Index(
                fields=["encounter", "-created_at"],
                name="clinical_pr_encount_19620e_idx",
            ),
        ),
    ]
