# Generated by Django 5.2.13 on 2026-04-10 07:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("generic_name", models.CharField(max_length=200)),
                (
                    "ndc_code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="NDC Code",
                    ),
                ),
                ("drug_class", models.CharField(blank=True, max_length=100)),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("injection", "Injection"),
                            ("syrup", "Syrup"),
                            ("cream", "Cream"),
                            ("ointment", "Ointment"),
                            ("drops", "Drops"),
                            ("inhaler", "Inhaler"),
                            ("patch", "Patch"),
                            ("suppository", "Suppository"),
                            ("iv_fluid", "IV Fluid"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("strength", models.CharField(max_length=50)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("requires_prescription", models.BooleanField(default=True)),
                (
                    "is_controlled",
                    models.BooleanField(
                        default=False, help_text="Controlled substance (DEA scheduled)"
                    ),
                ),
                ("contraindications", models.TextField(blank=True)),
                ("side_effects", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dosage", models.CharField(help_text='e.g., "500mg"', max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        help_text='e.g., "TID (three times daily)"', max_length=100
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("iv", "Intravenous"),
                            ("im", "Intramuscular"),
                            ("sc", "Subcutaneous"),
                            ("topical", "Topical"),
                            ("inhaled", "Inhaled"),
                            ("rectal", "Rectal"),
                            ("sublingual", "Sublingual"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("duration_days", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("refills_allowed", models.IntegerField(default=0)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Special instructions for patient"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dispensed", "Dispensed"),
                            ("completed", "Completed"),
                            ("discontinued", "Discontinued"),
                            ("on_hold", "On Hold"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("discontinued_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescribing_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DrugAdministration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("administered_at", models.DateTimeField()),
                ("dose_given", models.CharField(max_length=100)),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("iv", "Intravenous"),
                            ("im", "Intramuscular"),
                            ("sc", "Subcutaneous"),
                            ("topical", "Topical"),
                            ("inhaled", "Inhaled"),
                            ("rectal", "Rectal"),
                            ("sublingual", "Sublingual"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True, help_text='e.g., "left deltoid"', max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "patient_response",
                    models.TextField(
                        blank=True, help_text="Patient's response to medication"
                    ),
                ),
                ("was_refused", models.BooleanField(default=False)),
                ("refusal_reason", models.TextField(blank=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administered_drugs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrations",
                        to="pharmacy.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["-administered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["ndc_code"], name="pharmacy_dr_ndc_cod_6d9c90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["generic_name"], name="pharmacy_dr_generic_ce7297_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "-created_at"], name="pharmacy_pr_patient_e5426f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["status"], name="pharmacy_pr_status_3f9cad_idx"),
        ),
    ]
