# Generated by Django 5.2.13 on 2026-04-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CPTCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=5, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=200)),
                ("subcategory", models.CharField(blank=True, max_length=200)),
                (
                    "rvu",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Relative Value Unit",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("version_year", models.IntegerField(default=2026)),
            ],
            options={
                "verbose_name": "CPT Code",
                "verbose_name_plural": "CPT Codes",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="codes_cptco_code_eebedc_idx"),
                    models.Index(
                        fields=["category"], name="codes_cptco_categor_25e60e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ICD10Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=200)),
                ("chapter", models.CharField(blank=True, max_length=200)),
                ("is_billable", models.BooleanField(default=True)),
                ("version_year", models.IntegerField(default=2026)),
            ],
            options={
                "verbose_name": "ICD-10 Code",
                "verbose_name_plural": "ICD-10 Codes",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="codes_icd10_code_d37b8e_idx"),
                    models.Index(
                        fields=["category"], name="codes_icd10_categor_1a1be9_idx"
                    ),
                ],
            },
        ),
    ]
